CREATE TABLE USERS (
    USERNAME VARCHAR2(30) NOT NULL,
    PASSWORD VARCHAR2(50) NOT NULL,
    ACTIVE NUMBER(1) DEFAULT 1,
    CONSTRAINT USERS_FK PRIMARY KEY (USERNAME)
);

CREATE TABLE ROLES (
    USERNAME VARCHAR2(30) NOT NULL,
    ROLE VARCHAR2(15) DEFAULT 'Aspirante',
    CONSTRAINT USER_ROLE_FK FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);
